// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpPHX1SI1IiR2RBzlStCtDd87UNkH6Ox0',
    appId: '1:844685227697:web:32b49105cb80fcb6d31490',
    messagingSenderId: '844685227697',
    projectId: 'reddit-clone-1c665',
    authDomain: 'reddit-clone-1c665.firebaseapp.com',
    storageBucket: 'reddit-clone-1c665.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBJlXGZV3xbSJz1K-u1QiJ8Ltjx1PO4s',
    appId: '1:844685227697:android:63019f2de4cecbedd31490',
    messagingSenderId: '844685227697',
    projectId: 'reddit-clone-1c665',
    storageBucket: 'reddit-clone-1c665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hzPIAbkdj0y0dqtgPuRhRk7Xlbq_zKM',
    appId: '1:844685227697:ios:54ebb8cf6d7bd84fd31490',
    messagingSenderId: '844685227697',
    projectId: 'reddit-clone-1c665',
    storageBucket: 'reddit-clone-1c665.appspot.com',
    iosClientId: '844685227697-jemisg1492oetj3gdqeoqvrf6qud2s0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
